export const PROJECTS_LIST_REQUEST = "PROJECTS_LIST_REQUEST";
export const PROJECTS_LIST_SUCCESS = "PROJECTS_LIST_SUCCESS";
export const PROJECTS_LIST_FAIL = "PROJECTS_LIST_FAIL";

export const PROJECTS_CREATE_REQUEST = "PROJECTS_CREATE_REQUEST";
export const PROJECTS_CREATE_SUCCESS = "PROJECTS_CREATE_SUCCESS";
export const PROJECTS_CREATE_FAIL = "PROJECTS_CREATE_FAIL";

export const PROJECTS_UPDATE_REQUEST = "PROJECTS_UPDATE_REQUEST";
export const PROJECTS_UPDATE_SUCCESS = "PROJECTS_UPDATE_SUCCESS";
export const PROJECTS_UPDATE_FAIL = "PROJECTS_UPDATE_FAIL";

export const PROJECTS_DELETE_REQUEST = "PROJECTS_DELETE_REQUEST";
export const PROJECTS_DELETE_SUCCESS = "PROJECTS_DELETE_SUCCESS";
export const PROJECTS_DELETE_FAIL = "PROJECTS_DELETE_FAIL";
